spring:
  profiles:
    active: local
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false

---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
server:
  title: springBootRedisStudy-local
  port : 8080
  
redis:
  port : 7979

---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: true
  cache:
    type : redis
  redis:
    host: localhost
    port: 6379
         
server:
  title: springBootRedisStudy-prod
  port : 8081

 